### ISSUE TITLE
Capture click event from dropdown

### ISSUE THREAD

**Issue by pbarrientos** [ajlkn/jquery.dropotron#12]
Hello.
I'm checking a project that uses dropotron and can't accomplish something that seems pretty easy.
I wonder how do I capture the click event from the dropdown list on the top menu.
http://html5up.net/telephasic
I've been trying to log the mouse events on the console but it seems all mouse events on the dropdown are disabled.
Any ideas?
Thanks in advance.

**Comment by ajlkn** [comment]
Not sure if this is still an issue, but if it is please reopen it!

**Comment by ndbroadbent** [comment]
Yeah it seems like I can't capture any click events from links in the dropdown. I prefer to use jQuery's `on` function to attach an event listener to `document`, but I think dropotron is calling `event.preventDefault()` somewhere, which stops the listener from seeing the click.
