### ISSUE TITLE
menuClass: 'dropotron' won't be added

### ISSUE THREAD

**Issue by herrfischer** [ajlkn/jquery.dropotron#13]
Tried in the demo i downloaded here. It has no effect:

    $('#main-nav > ul').dropotron({ 
	    offsetY: -10, 
	    menuClass: 'dropotron',
	    expandMode: 'click'
    });

EDIT: sorry now i see it's only added to the pulldowns.

**Comment by ajlkn** [comment]
Yup :+1:
