### ISSUE TITLE
Detach and cloneOnDetach break dropotron in iOS Safari

### ISSUE THREAD

**Issue by mdkraft** [ajlkn/jquery.dropotron#15]
When I switch detach and cloneOnDetach to false, the dropdown stops appearing in iOS Safari. When viewing from an iPad or the iOS Simulator to the Web Inspector in Safari for Mac, I can see that when the dropdown is tapped, the UL that contains the menu items flickers between display:none and display:block numerous times before settling back on display:none. Any ideas?

`offsetY: 0,
baseZIndex: 9000000,
mode: 'instant',
alignment: 'right',
noOpenerFade: true,
detach: false,
cloneOnDetach: false,
expandMode: (skel.vars.isTouch ? 'click' : 'hover')`

**Comment by ajlkn** [comment]
Not sure if this is still an issue, but if it is please reopen it!
