### ISSUE TITLE
Incorrect position with inline submenu

### ISSUE THREAD

**Issue by UnickSoft** [ajlkn/jquery.dropotron#7]
Hello.

I added inline sub-menu to your demo: https://github.com/UnickSoft/jquery.dropotron/blob/master/demo/demo1.html

It is shown incorrectly on first time, but correct on the next time.

First time:
![image](https://cloud.githubusercontent.com/assets/9623833/5695665/ba315e8e-99b6-11e4-8aef-9acc4875b822.png)

Second time:
![image](https://cloud.githubusercontent.com/assets/9623833/5695668/c6b1c1f8-99b6-11e4-84c1-1f45cdc0928e.png)

Maybe I used droptron wrong.

**Comment by n33** [comment]
Can you reproduce this behavior in browsers besides Opera?

**Comment by UnickSoft** [comment]
In Google Chrome I have little another bugs. I attached pictures. Menu have new position on each mouseover.

![menu2](https://cloud.githubusercontent.com/assets/9623833/6488339/8524595a-c29f-11e4-9080-84328af9e926.png)
![menu1](https://cloud.githubusercontent.com/assets/9623833/6488340/85269e7c-c29f-11e4-8439-5dd617397617.png)

**Comment by n33** [comment]
Yep, some calculation's probably off.

**Comment by ajlkn** [comment]
Not sure if this is still an issue, but if it is please reopen it!
